language: python
python:
 - "2.7"
install:
 - pip install flake8 --use-mirrors
 - sudo apt-get install nodejs
 - sudo npm install -g jshint
script:
 - flake8 .
 - jshint *.js{,on.dist} services/*.js{,on.dist}
